### PR TITLE
Implementing LIFX API for turning on lights with fade-in when alarm goes...

### PR DESCRIPTION
**Pull request by jorgerdz**
I added a few things so that the app uses the LIFX (smart lights) cloud API to turn on lights with a fade-in when an alarm goes off. The website would also have to be updated with these changes so that the users can update their LIFX token which is needed for the API.

### CODE REVIEW

**Comment by JamesFowler42** [comment]
Hi, happy to include this - sorry I've been out of the loop for a little while. It seems like a nice addition to Morpheuz - thanks. My next release, is, as you'd expect, to include colour and support for Pebble Time but after that I want to get this one in.

**Comment by JamesFowler42** [comment]
Implementing in version 3.1 - if you want to beta test this, please reply.

**Comment by alin256** [comment]
I would love to participate in testing. Is LIFX conpatible with philis hue?

**Comment by JamesFowler42** [comment]
I believe not.

**Comment by jorgerdz** [comment]
@alin256 Unfortunately not, I would have to implement a different interface for the Hue, and I don't own one so testing would be difficult.

@JamesFowler42 Sure thing, let me know what I can do to help with testing.

**Pull request merged**
